/**
 * Idempotent CREATE TABLE IF NOT EXISTS guard for the three agent-* tables.
 * Matches the codebase's existing ensure-schema pattern (lib/db/ensure-
 * schema.ts) so a fresh serverless instance's first request DDLs the tables
 * without a separate migration step — the same trade-off every other table
 * in this app already accepts.
 */
import { sql } from "drizzle-orm";
import { db } from "@/lib/db";

let ensured = false;

export async function ensureAgentTables(): Promise<void> {
  if (ensured) return;
  try {
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS agent_runs (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id),
        campaign_id uuid REFERENCES campaigns(id) ON DELETE SET NULL,
        status varchar(32) NOT NULL DEFAULT 'pending',
        goal text NOT NULL,
        input jsonb DEFAULT '{}'::jsonb,
        output jsonb,
        error_message text,
        started_at timestamptz NOT NULL DEFAULT now(),
        completed_at timestamptz,
        updated_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_runs_user ON agent_runs(user_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_runs_campaign ON agent_runs(campaign_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON agent_runs(user_id, status);`);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS agent_tasks (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        run_id uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
        agent_name varchar(64) NOT NULL,
        status varchar(32) NOT NULL DEFAULT 'pending',
        input jsonb DEFAULT '{}'::jsonb,
        output jsonb,
        error_message text,
        sequence integer NOT NULL DEFAULT 0,
        started_at timestamptz NOT NULL DEFAULT now(),
        completed_at timestamptz
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_tasks_run ON agent_tasks(run_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_tasks_agent ON agent_tasks(agent_name, status);`);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS agent_logs (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        task_id uuid NOT NULL REFERENCES agent_tasks(id) ON DELETE CASCADE,
        level varchar(16) NOT NULL DEFAULT 'info',
        message text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_logs_task ON agent_logs(task_id, created_at);`);

    // reply_drafts — auto-drafts generated by the Reply Handler Agent.
    // Kept as a separate table (rather than a column on `replies`) so we
    // can retain a per-draft history (multiple runs, manual edits) and
    // track auto-send state independently of the reply's own action state.
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS reply_drafts (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        reply_id uuid NOT NULL REFERENCES replies(id) ON DELETE CASCADE,
        intent varchar(64) NOT NULL,
        draft_body text NOT NULL,
        draft_subject varchar(500),
        auto_sent boolean DEFAULT false,
        sent_at timestamptz,
        external_message_id varchar(500),
        error text,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_reply_drafts_user ON reply_drafts(user_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_reply_drafts_reply ON reply_drafts(reply_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_reply_drafts_unsent ON reply_drafts(user_id, sent_at);`);

    // agent_run_id backfill on outreach_messages — added late so it must
    // be added idempotently rather than baked into the CREATE TABLE.
    await db.execute(sql`
      ALTER TABLE outreach_messages
      ADD COLUMN IF NOT EXISTS agent_run_id uuid REFERENCES agent_runs(id) ON DELETE SET NULL;
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_outreach_messages_agent_run ON outreach_messages(agent_run_id);`);

    ensured = true;
  } catch (err) {
    console.error("[agents] ensureAgentTables failed:", err);
  }
}
