/**
 * Idempotent CREATE TABLE IF NOT EXISTS guard for the three agent-* tables.
 * Matches the codebase's existing ensure-schema pattern (lib/db/ensure-
 * schema.ts) so a fresh serverless instance's first request DDLs the tables
 * without a separate migration step — the same trade-off every other table
 * in this app already accepts.
 */
import { sql } from "drizzle-orm";
import { db } from "@/lib/db";

let ensured = false;

export async function ensureAgentTables(): Promise<void> {
  if (ensured) return;
  try {
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS agent_runs (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id),
        campaign_id uuid REFERENCES campaigns(id) ON DELETE SET NULL,
        status varchar(32) NOT NULL DEFAULT 'pending',
        goal text NOT NULL,
        input jsonb DEFAULT '{}'::jsonb,
        output jsonb,
        error_message text,
        started_at timestamptz NOT NULL DEFAULT now(),
        completed_at timestamptz,
        updated_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_runs_user ON agent_runs(user_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_runs_campaign ON agent_runs(campaign_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON agent_runs(user_id, status);`);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS agent_tasks (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        run_id uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
        agent_name varchar(64) NOT NULL,
        status varchar(32) NOT NULL DEFAULT 'pending',
        input jsonb DEFAULT '{}'::jsonb,
        output jsonb,
        error_message text,
        sequence integer NOT NULL DEFAULT 0,
        started_at timestamptz NOT NULL DEFAULT now(),
        completed_at timestamptz
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_tasks_run ON agent_tasks(run_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_tasks_agent ON agent_tasks(agent_name, status);`);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS agent_logs (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        task_id uuid NOT NULL REFERENCES agent_tasks(id) ON DELETE CASCADE,
        level varchar(16) NOT NULL DEFAULT 'info',
        message text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_agent_logs_task ON agent_logs(task_id, created_at);`);

    // reply_drafts — auto-drafts generated by the Reply Handler Agent.
    // Kept as a separate table (rather than a column on `replies`) so we
    // can retain a per-draft history (multiple runs, manual edits) and
    // track auto-send state independently of the reply's own action state.
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS reply_drafts (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        reply_id uuid NOT NULL REFERENCES replies(id) ON DELETE CASCADE,
        intent varchar(64) NOT NULL,
        draft_body text NOT NULL,
        draft_subject varchar(500),
        auto_sent boolean DEFAULT false,
        sent_at timestamptz,
        external_message_id varchar(500),
        error text,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_reply_drafts_user ON reply_drafts(user_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_reply_drafts_reply ON reply_drafts(reply_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_reply_drafts_unsent ON reply_drafts(user_id, sent_at);`);

    // agent_run_id backfill on outreach_messages — added late so it must
    // be added idempotently rather than baked into the CREATE TABLE.
    await db.execute(sql`
      ALTER TABLE outreach_messages
      ADD COLUMN IF NOT EXISTS agent_run_id uuid REFERENCES agent_runs(id) ON DELETE SET NULL;
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_outreach_messages_agent_run ON outreach_messages(agent_run_id);`);

    // LinkedIn outreach tracking
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS linkedin_outreach (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
        profile_url text NOT NULL,
        action varchar(32) NOT NULL DEFAULT 'connection_request',
        message text,
        status varchar(32) NOT NULL DEFAULT 'pending',
        sent_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_linkedin_outreach_user ON linkedin_outreach(user_id);`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_linkedin_outreach_lead ON linkedin_outreach(lead_id);`);

    // CRM integrations
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS crm_integrations (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        provider varchar(32) NOT NULL,
        access_token text,
        refresh_token text,
        instance_url text,
        settings jsonb DEFAULT '{}'::jsonb,
        last_synced_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_integrations_user_provider ON crm_integrations(user_id, provider);`);

    // WhatsApp messages
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS whatsapp_messages (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
        campaign_id uuid REFERENCES campaigns(id) ON DELETE SET NULL,
        to_number varchar(32) NOT NULL,
        body text NOT NULL,
        status varchar(32) NOT NULL DEFAULT 'pending',
        external_sid varchar(128),
        sent_at timestamptz,
        delivered_at timestamptz,
        read_at timestamptz,
        error text,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_user ON whatsapp_messages(user_id);`);

    // Voice calls
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS voice_calls (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
        campaign_id uuid REFERENCES campaigns(id) ON DELETE SET NULL,
        to_number varchar(32) NOT NULL,
        duration integer DEFAULT 0,
        status varchar(32) NOT NULL DEFAULT 'pending',
        transcript text,
        outcome varchar(64),
        recording_url text,
        external_sid varchar(128),
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_voice_calls_user ON voice_calls(user_id);`);

    // SMS messages
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS sms_messages (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
        campaign_id uuid REFERENCES campaigns(id) ON DELETE SET NULL,
        to_number varchar(32) NOT NULL,
        body text NOT NULL,
        status varchar(32) NOT NULL DEFAULT 'pending',
        external_sid varchar(128),
        sent_at timestamptz,
        error text,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_sms_messages_user ON sms_messages(user_id);`);

    // Warmup sessions
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS warmup_sessions (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        mailbox_email varchar(320) NOT NULL,
        status varchar(32) NOT NULL DEFAULT 'active',
        started_at timestamptz NOT NULL DEFAULT now(),
        paused_at timestamptz,
        daily_limit integer NOT NULL DEFAULT 5,
        health_score integer NOT NULL DEFAULT 50,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_warmup_sessions_user ON warmup_sessions(user_id);`);

    // Warmup emails
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS warmup_emails (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        session_id uuid NOT NULL REFERENCES warmup_sessions(id) ON DELETE CASCADE,
        direction varchar(16) NOT NULL DEFAULT 'outbound',
        subject varchar(500),
        status varchar(32) NOT NULL DEFAULT 'sent',
        sent_at timestamptz NOT NULL DEFAULT now(),
        replied_at timestamptz,
        bounced_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now()
      );
    `);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_warmup_emails_session ON warmup_emails(session_id);`);

    ensured = true;
  } catch (err) {
    console.error("[agents] ensureAgentTables failed:", err);
  }
}
